version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - local-net
  
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.core.celery_worker.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    networks:
      - local-net
  
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.core.celery_worker.celery flower --port=5555
    env_file:
      - .env
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - celery_worker
    networks:
      - local-net
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    networks:
      - local-net
    ports:
      - "8101:8000"
    volumes:
      - ./app:/app/app


networks:
  local-net:
    driver: bridge