version: '3'

networks:
  local-net:
    driver: bridge

services:
  db:
    container_name: '${POSTGRES_SERVER}'
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - local-net
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
  
  redis:
    container_name: '${REDIS_SERVER}'
    image: redis:latest
    networks:
      - local-net
    env_file:
      - .env

  database:
    container_name: '${DATABASE_SVC}'
    build: ./database
    command: uvicorn 
      app.main:app 
      --host=0.0.0.0
      --port ${DATABASE_PORT}
      --reload
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - local-net
    volumes:
      - ./database:/app
    ports:
      - 8000:${DATABASE_PORT}