apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - targetPort: 8003
      port: 8003
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: simon3640/guane-gateway
          command: 
            - uvicorn
          args: 
            - app.main:app
            - --host=0.0.0.0
            - --port=8003
            - --reload
          ports:
            - containerPort: 8003
          envFrom:
          - secretRef:
              name: env